added parameter validation and allow trust store creation

diff --git a/pyki-jks b/pyki-jks
--- a/pyki-jks
+++ b/pyki-jks
@@ -1,18 +1,34 @@
 #!/bin/bash
 
-# usage:
-#
-# pyki-jks  --keystore KEYSTORE --password PASSWORD --key KEY --cert CERT CA1 CA2 ...
-#
-# --keystore www.jks --password inc0rrect --key www.key --cert www.crt ca.crt
+usage() {
+  cat <<EOF | sed 's/^  //'
+  Usage: 
 
-echo "'$@'"
+    To create server key store:
+    pyki-jks  --keystore KEYSTORE --password PASSWORD --key KEY --cert CERT CA* ...
+    pyki-jks  --keystore www.jks --password inc0rrect --key www.key --cert www.crt ca.crt
+
+    To create CA trust store:
+    pyki-jks  --keystore KEYSTORE --password PASSWORD CA* ...
+    pyki-jks  --keystore www.jks --password inc0rrect ca.crt
+    
+EOF
+  exit 2
+}
+
+require() {
+  S=$(eval "echo \$$1")
+  if [ -z "$S" ]; then
+    echo "Parameter --${1,,} missing"
+    usage
+  fi
+}
 
 ARGS=$(getopt -a -n pyki-jks -o K:p:k:c: --long keystore:,password:,key:,cert: -- "$@")
 
 ERROR=$?
 if [ $ERROR != 0 ]; then 
-    echo "Incorrect options provided"
+    usage
     exit 1
 fi
 
@@ -29,22 +45,35 @@ do
   esac
 done
 
+require KEYSTORE
+require PASSWORD
+
+if [ -n "$KEY" ]; then
+  require CERT
+fi
+
+if [ -n "$CERT" ]; then
+  require KEY
+fi
+
 rm -f "${KEYSTORE}"
 
 KS=$(mktemp /tmp/XXXXXXXXXXX)
 
-openssl pkcs12 -export \
-  -password "pass:${PASSWORD}" \
-  -inkey "${KEY}" \
-  -in    "${CERT}" \
-  -name "server" \
-  -out "${KS}"
+if [ -n "$KEY" ]; then
+  openssl pkcs12 -export \
+    -password "pass:${PASSWORD}" \
+    -inkey "${KEY}" \
+    -in    "${CERT}" \
+    -name "server" \
+    -out "${KS}"
 
-keytool -importkeystore \
-  -srckeystore "${KS}" -srcstoretype PKCS12 \
-  -srcstorepass "${PASSWORD}" \
-  -destkeystore "${KEYSTORE}" -deststoretype JKS \
-  -deststorepass "${PASSWORD}" 
+  keytool -importkeystore \
+    -srckeystore "${KS}" -srcstoretype PKCS12 \
+    -srcstorepass "${PASSWORD}" \
+    -destkeystore "${KEYSTORE}" -deststoretype JKS \
+    -deststorepass "${PASSWORD}" 
+fi
 
 N=1
 for CA in $@; do
